set -g status on
set -g status-interval 1
set -g status-bg black
set -g status-fg white

set -g status-left-length 50
set -g status-right-length 50

set -g status-left "#[fg=black,bg=green] #S #[fg=green,bg=blue] #[fg=white,bg=blue] #W #[fg=blue,bg=black]"
set -g status-right "#[fg=black,bg=yellow] %H:%M "
